name: PHP Tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: installing phpmd dependency
        run: composer require phpmd/phpmd

      - name: install phpcs locally
        run: composer require squizlabs/php_codesniffer

      - name: php md 
        run: ./vendor/bin/phpmd index.php text .

      - name: PHP CodeSniffer (PHP CS)
        run: ./vendor/bin/phpcs --standard=PSR12 .

      - name: php cbf
        run: ./vendor/bin/phpcbf --standard=PSR12 .

      - name: Check syntax php lint
        run: php -l index.php


